name: CI

on: [push]

jobs:
  sast_scan:
    name: Run Bandit Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit Scan
        run: bandit -ll -ii -r .

  image_scan:
    name: Build Image and Run Image Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@v1
        with: 
          docker_version: '20.10.7'

      - name: Verify Docker Installation
        run: |
          docker --version
          sudo systemctl status docker || true

      - name: Build Docker Image
        run: |
          echo "Building Docker image..."
          docker build -f Dockerfile -t myapp:latest .

      - name: Docker Login
        run: echo "${{ secrets.REPO_TOKEN }}" | docker login -u pearlgerome --password-stdin


      - name: Install Docker Scout
        run: |
          curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
          sh install-scout.sh

      - name: Run Docker Scout Scan
        run: |
          docker scout quickview
          docker scout cves
