name: CI

on: [push]

jobs:
  image_scan:
    name: Build Image and Run Image Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Docker Login
        run: echo "${{ secrets.REPO_TOKEN }}" | docker login -u "${{ secrets.REPO_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -f Dockerfile -t myapp:latest .

      - name: Run Docker Scout Scan
        run: |
          docker scout quickview
          docker scout cves
