name: CI

on: [push]

jobs:
  image_scan:
    name: Build Image and Run Image Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker (if not installed)
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          sudo systemctl enable docker
          docker --version

      - name: Verify Docker Status
        run: |
          sudo systemctl status docker
          docker info

      - name: Docker Login
        run: echo "${{ secrets.REPO_TOKEN }}" | docker login -u "${{ secrets.REPO_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: docker build -f Dockerfile -t myapp:latest .

      - name: Run Docker Scout Scan
        run: |
          docker scout quickview
          docker scout cves
