name: CI

on: [push]

jobs:
  image_scan:
    name: Build Image and Run Image Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker-practice/actions-setup-docker@v1
        with:
          docker_version: '20.10.7'

      - name: Verify Docker Installation
        run: |
          docker --version
          sudo systemctl status docker || true

      - name: Build Docker Image
        run: |
          echo "Building Docker image..."
          docker build -f Dockerfile -t myapp:latest .

      - name: Show Docker Login Info
        run: |
          echo "Docker username: ${{ secrets.REPO_USERNAME }}"
          echo "Docker token: ${{ secrets.REPO_TOKEN }}"  # **Don't do this on real runs as it may leak secrets!**
        env:
          REPO_USERNAME: ${{ secrets.REPO_USERNAME }}
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}

      - name: Docker Login
        run: |
          echo "Logging into Docker..."
          echo "${{ secrets.REPO_TOKEN }}" | docker login -u "${{ secrets.REPO_USERNAME }}" --password-stdin
          
      - name: Run Docker Scout Scan
        run: |
          docker scout quickview
          docker scout cves
